CREATE DATABASE SistemaPatrimonio
GO

USE SistemaPatrimonio
GO

CREATE TABLE TipoAlteracao(
TipoAlteracaoID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
Tipo VARCHAR(50) UNIQUE NOT NULL
);
GO

CREATE TABLE Area(
AreaID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
NomeArea VARCHAR(50) UNIQUE NOT NULL
);
GO

CREATE TABLE StatusTransferencia(
StatusTransferenciaID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
[Status] VARCHAR(50) UNIQUE NOT NULL
);
GO

CREATE TABLE StatusPatrimonio(
StatusPatrimonioID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
[Status] VARCHAR(50) UNIQUE NOT NULL
);
GO

CREATE TABLE TipoPatrimonio(
TipoPatrimonioID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
NomeTipo VARCHAR(100) UNIQUE NOT NULL
);
GO

CREATE TABLE Cidade(
CidadeID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
NomeCidade VARCHAR(50) NOT NULL,
Estado VARCHAR(50) NOT NULL
);
GO

CREATE TABLE Bairro(
BairroID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
NomeBairro VARCHAR(50) NOT NULL,
CidadeID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Cidade(CidadeID)
);
GO

CREATE TABLE Endereco(
EnderecoID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
Logradouro VARCHAR(100) NOT NULL,
Numero INT NOT NULL,
Complemento VARCHAR(50),
CEP VARCHAR(10) NOT NULL,
BairroID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Bairro(BairroID)
);
GO

CREATE TABLE TipoUsuario(
TipoUsuarioID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
NomeTipo VARCHAR(50) UNIQUE NOT NULL
);
GO

CREATE TABLE Cargo(
CargoID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
NomeCargo VARCHAR(50) UNIQUE NOT NULL
);
GO

CREATE TABLE Usuario(
UsuarioID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
NIF VARCHAR(7) UNIQUE NOT NULL,
Nome VARCHAR(150) NOT NULL,
RG VARCHAR(15) UNIQUE NOT NULL,
CPF VARCHAR(11) UNIQUE NOT NULL,
CarteiraTrabalho VARCHAR(14) UNIQUE NOT NULL,
Senha VARBINARY(32) NOT NULL,
Email VARCHAR(150) UNIQUE NOT NULL,
EnderecoID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Endereco(EnderecoID),
CargoID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Cargo(CargoID) ,
TipoUsuarioID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoUsuario(TipoUsuarioID) 
);
GO


CREATE TABLE [Local](
LocalID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
Nome VARCHAR(100) NOT NULL,
LocalSap INT,
Descricao VARCHAR(100),
AreaID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Area(AreaID) ON DELETE CASCA
DE
);
GO

CREATE TABLE LocalUsuario(
UsuarioID UNIQUEIDENTIFIER,
LocalLocalUsuarioID UNIQUEIDENTIFIER,

    
CONSTRAINT PK_LocalUsuario PRIMARY KEY (UsuarioID, LocalLocalUsuarioID),
CONSTRAINT FK_Usuario FOREIGN KEY (UsuarioID) REFERENCES Usuario(UsuarioID)ON DELETE CASCADE,
CONSTRAINT FK_Local FOREIGN KEY (LocalLocalUsuarioID) REFERENCES [Local](LocalID) ON DELETE CASCADE
);
GO

CREATE TABLE Patrimonio(
PatrimonioID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
Denominacao VARCHAR(MAX) NOT NULL,
NumeroSerie VARCHAR(50) UNIQUE NOT NULL,
Valor DECIMAL(10,2) NOT NULL,
Imagem VARCHAR(MAX) NOT NULL,
LocalID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Local](LocalID) ,
TipoPatrimonioID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoPatrimonio(TipoPatrimonioID) ,
StatusPatrimonioID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES StatusPatrimonio(StatusPatrimonioID) 
);

CREATE TABLE SolicitacaoTransferencia(
TransferenciaID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
DataCriacaoSolicitacao DATETIME NULL,
DataResposta DATETIME NULL,
Justificativa VARCHAR(MAX) NOT NULL,
PatrimonioID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Patrimonio(PatrimonioID) ,
StatusTransferenciaID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES StatusTransferencia(StatusTransferenciaID) ,
StatusPatrimonioID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES StatusPatrimonio(StatusPatrimonioID) ,
UsuarioIDSolicitacao UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(UsuarioID) ,
UsuarioIDAprovacao UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(UsuarioID) ,
LocalID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Local](LocalID) 
);

CREATE TABLE Log_Patrimonio(
LogPatrimonioID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
DataTransferencia DATETIME UNIQUE NOT NULL,
TipoAlteracaoID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoAlteracao(TipoAlteracaoID),
PatrimonioID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Patrimonio(PatrimonioID) ,
UsuarioID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(UsuarioID),
LocalID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Local](LocalID),
StatusPatrimonioID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES StatusPatrimonio(StatusPatrimonioID)
);
