CREATE DATABASE SistemaPatrimonio
GO

USE SistemaPatrimonio
GO

CREATE TABLE TipoAlteracao(
TipoAlteracaoID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
Tipo VARCHAR(50) UNIQUE NOT NULL
);
GO

CREATE TABLE Area(
AreaID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
NomeArea VARCHAR(50) UNIQUE NOT NULL
);
GO

CREATE TABLE StatusTransferencia(
StatusTransferenciaID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
[Status] VARCHAR(50) UNIQUE NOT NULL
);
GO

CREATE TABLE StatusPatrimonio(
StatusPatrimonioID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
[Status] VARCHAR(50) UNIQUE NOT NULL
);
GO

CREATE TABLE TipoPatrimonio(
TipoPatrimonioID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
NomeTipo VARCHAR(100) UNIQUE NOT NULL
);
GO

CREATE TABLE Cidade(
CidadeID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
NomeCidade VARCHAR(50) NOT NULL,
Estado VARCHAR(50) NOT NULL
);
GO

CREATE TABLE Bairro(
BairroID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
NomeBairro VARCHAR(50) NOT NULL,
CidadeID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Cidade(CidadeID) NOT NULL
);
GO

CREATE TABLE Endereco(
EnderecoID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
Logradouro VARCHAR(100) NOT NULL,
Numero INT NOT NULL,
Complemento VARCHAR(50),
CEP VARCHAR(10) NOT NULL,
BairroID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Bairro(BairroID) NOT NULL
);
GO

CREATE TABLE TipoUsuario(
TipoUsuarioID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
NomeTipo VARCHAR(50) UNIQUE NOT NULL
);
GO

CREATE TABLE Cargo(
CargoID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
NomeCargo VARCHAR(50) UNIQUE NOT NULL
);
GO

CREATE TABLE Usuario(
UsuarioID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
NIF VARCHAR(7) UNIQUE NOT NULL,
Nome VARCHAR(150) NOT NULL,
RG VARCHAR(15) UNIQUE,
CPF VARCHAR(11) UNIQUE NOT NULL,
CarteiraTrabalho VARCHAR(14) UNIQUE NOT NULL,
Senha VARBINARY(32) NOT NULL,
Email VARCHAR(150) UNIQUE NOT NULL,
Ativo BIT DEFAULT 1,
EnderecoID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Endereco(EnderecoID) NOT NULL,
CargoID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Cargo(CargoID) NOT NULL,
TipoUsuarioID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoUsuario(TipoUsuarioID) NOT NULL
);
GO


CREATE TABLE [Local](
LocalID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
Nome VARCHAR(100) NOT NULL,
LocalSap INT,
Descricao VARCHAR(100),
Ativo BIT DEFAULT 1,
AreaID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Area(AreaID) NOT NULL
);
GO

CREATE TABLE LocalUsuario(
UsuarioID UNIQUEIDENTIFIER NOT NULL,
LocalLocalUsuarioID UNIQUEIDENTIFIER NOT NULL,

    
CONSTRAINT PK_LocalUsuario PRIMARY KEY (UsuarioID, LocalLocalUsuarioID),
CONSTRAINT FK_Usuario FOREIGN KEY (UsuarioID) REFERENCES Usuario(UsuarioID) ,
CONSTRAINT FK_Local FOREIGN KEY (LocalLocalUsuarioID) REFERENCES [Local](LocalID)
);
GO

CREATE TABLE Patrimonio(
PatrimonioID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
Denominacao VARCHAR(MAX) NOT NULL,
NumeroPatrimonio VARCHAR(50) UNIQUE NOT NULL,
Valor DECIMAL(10,2),
Imagem VARCHAR(MAX) NOT NULL,
LocalID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Local](LocalID) NOT NULL,
TipoPatrimonioID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoPatrimonio(TipoPatrimonioID) NOT NULL,
StatusPatrimonioID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES StatusPatrimonio(StatusPatrimonioID) NOT NULL
);
GO

CREATE TABLE SolicitacaoTransferencia(
TransferenciaID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
DataCriacaoSolicitante DATETIME2(0) NOT NULL,
DataResposta DATETIME2(0),
Justificativa VARCHAR(MAX) NOT NULL,
PatrimonioID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Patrimonio(PatrimonioID) NOT NULL ,
StatusTransferenciaID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES StatusTransferencia(StatusTransferenciaID) NOT NULL,
StatusPatrimonioID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES StatusPatrimonio(StatusPatrimonioID) NOT NULL,
UsuarioIDSolicitacao UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(UsuarioID) NOT NULL,
UsuarioIDAprovacao UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(UsuarioID),
LocalID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Local](LocalID) NOT NULL
);
GO

CREATE TABLE Log_Patrimonio(
LogPatrimonioID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
DataTransferencia DATETIME2(0) NOT NULL,
TipoAlteracaoID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoAlteracao(TipoAlteracaoID) NOT NULL,
PatrimonioID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Patrimonio(PatrimonioID) NOT NULL ,
UsuarioID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(UsuarioID) NOT NULL,
LocalID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Local](LocalID) NOT NULL,
StatusPatrimonioID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES StatusPatrimonio(StatusPatrimonioID) NOT NULL
);
GO

CREATE TRIGGER trg_Usuario_SoftDelete
ON Usuario
INSTEAD OF DELETE
AS
BEGIN
    UPDATE Usuario
        SET Ativo = 0
        WHERE UsuarioID IN (SELECT UsuarioID FROM deleted);
END
GO

CREATE TRIGGER trg_Local_SoftDelete
ON [Local]
INSTEAD OF DELETE
AS
BEGIN
    UPDATE [Local]
        SET Ativo = 0
        WHERE LocalID IN (SELECT LocalID FROM deleted);
END
GO


CREATE TRIGGER trg_Patrimonio_SoftDelete
ON Patrimonio
INSTEAD OF DELETE
AS
BEGIN
    UPDATE Patrimonio
        SET StatusPatrimonioID = (SELECT StatusPatrimonioID FROM StatusPatrimonio WHERE [Status] = 'Inativo')    
        WHERE PatrimonioID IN (SELECT PatrimonioID FROM deleted);
END
GO